title: 岐阜県美濃市
description: 岐阜県美濃市内でテイクアウトできるお店
data_url: https://docs.google.com/spreadsheets/d/1RwNKmXiLfEuPAb7WqG15k79xWJtNDrHyA4fiNwHgSMg/export?format=csv&gid=0
repository: https://github.com/rnsk/iemeshi/
form_url: ''
